# Generated by Django 5.2.9 on 2025-12-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
    ]
