# Generated by Django 5.2.9 on 2025-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='information_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('GIFT_IDEA', 'Gift Idea'), ('INTEREST', 'Interest'), ('PET', 'Pet'), ('FEAR', 'Fear'), ('HOBBY', 'Hobby'), ('JOB', 'Job'), ('FAMILY', 'Family'), ('CONFLICT', 'Conflict'), ('STATEMENT', 'Statement'), ('LIKES', 'Likes'), ('LIKES_NOT', 'Likes not')], default='GENERAL', max_length=255),
        ),
    ]
