# Generated by Django 5.2.9 on 2025-12-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_contacts', '0002_alter_contactinformation_information_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Informations'},
        ),
    ]
