# Generated by Django 5.2.9 on 2025-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contacts', '0003_alter_contactinformation_options'),
        ('_global', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts_tagged', to='_global.tag'),
        ),
    ]
