# Generated by Django 5.2.9 on 2025-12-05 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_contacts', '0003_alter_contactinformation_options'),
        ('_global', '0001_initial'),
        ('_shopping', '0004_alter_shoppinglist_options_and_more'),
        ('_tasks', '0001_initial'),
        ('_trips', '0002_alter_activity_options_alter_tripfile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='documents_tagged', to='_global.tag')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='buckets', to='_contacts.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets_created', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(blank=True, related_name='buckets', to='_shopping.recipe')),
                ('shopping_lists', models.ManyToManyField(blank=True, related_name='buckets', to='_shopping.shoppinglist')),
                ('tasks', models.ManyToManyField(blank=True, related_name='buckets', to='_tasks.task')),
                ('trips', models.ManyToManyField(blank=True, related_name='buckets', to='_trips.trip')),
                ('documents', models.ManyToManyField(blank=True, related_name='buckets', to='_buckets.document')),
                ('files', models.ManyToManyField(blank=True, related_name='buckets', to='_buckets.file')),
                ('images', models.ManyToManyField(blank=True, related_name='buckets', to='_buckets.image')),
                ('links', models.ManyToManyField(blank=True, related_name='buckets', to='_buckets.link')),
            ],
        ),
    ]
