# Generated by Django 5.2.9 on 2025-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_buckets', '0001_initial'),
        ('_global', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='buckets_tagged', to='_global.tag'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files_tagged', to='_global.tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images_tagged', to='_global.tag'),
        ),
    ]
