# Generated by Django 5.2.9 on 2025-12-03 11:23

import _trips.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=510)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=510, null=True)),
                ('extra_infos', models.TextField(blank=True, null=True)),
                ('optional', models.BooleanField(default=False)),
            ],
            bases=(_trips.models.TimelineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('AIRPLANE', 'Airplane'), ('CAR', 'Car'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('WALK', 'Walk'), ('MAIN', 'Main Activity'), ('WAITING', 'Waiting / Buffer')], max_length=255)),
                ('name', models.CharField(max_length=510)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('location_start', models.CharField(blank=True, max_length=510, null=True)),
                ('location_end', models.CharField(blank=True, max_length=510, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='_trips.event')),
            ],
            bases=(_trips.models.TimelineMixin, models.Model),
        ),
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='_trips.trip'),
        ),
        migrations.CreateModel(
            name='TripFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='trip_files/')),
                ('name', models.CharField(help_text="e.g. 'Flight Ticket' or 'Menu'", max_length=255)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='_trips.activity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='_trips.event')),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='trip_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='_trips.activity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='_trips.event')),
            ],
        ),
        migrations.CreateModel(
            name='TripLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(help_text="e.g. 'Restaurant Website'", max_length=255)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='_trips.activity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='_trips.event')),
            ],
        ),
    ]
