# Generated by Django 5.2.9 on 2025-12-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='tripfile',
            options={'verbose_name': 'Trip File', 'verbose_name_plural': 'Trip Files'},
        ),
        migrations.AlterModelOptions(
            name='tripimage',
            options={'verbose_name': 'Trip Image', 'verbose_name_plural': 'Trip Images'},
        ),
        migrations.AlterModelOptions(
            name='triplink',
            options={'verbose_name': 'Trip Link', 'verbose_name_plural': 'Trip Links'},
        ),
    ]
