# Generated by Django 5.2.9 on 2025-12-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_shopping', '0002_shoppinglist_is_archived_shoppinglist_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=models.TextField(default='hh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='shopping_list',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='_shopping.shoppinglist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='amount_unit',
            field=models.CharField(choices=[('GRAMM', 'Gramm'), ('MILLILITER', 'Milliliter'), ('TABLE_SPOONS', 'Table Spoons'), ('TEA_SPOONS', 'Tea Spoons'), ('PIECES', 'Pieces'), ('PACKAGES', 'Packages'), ('BOTTLES', 'Bottles')], default='GRAMM', max_length=255),
        ),
    ]
