# Generated by Django 5.2.9 on 2025-12-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_shopping', '0003_recipe_content_recipe_shopping_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Shopping List', 'verbose_name_plural': 'Shopping Lists'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'verbose_name': 'Shopping List Item', 'verbose_name_plural': 'Shopping List Items'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'verbose_name': 'Storage Location', 'verbose_name_plural': 'Storage Locations'},
        ),
        migrations.AlterModelOptions(
            name='storagelocationitem',
            options={'verbose_name': 'Storage Location Item', 'verbose_name_plural': 'Storage Location Items'},
        ),
    ]
