# Generated by Django 5.2.9 on 2025-12-03 11:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_global', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timebox_date_start', models.DateField(blank=True, null=True)),
                ('timebox_time_start', models.TimeField(blank=True, null=True)),
                ('timebox_date_end', models.DateField(blank=True, null=True)),
                ('timebox_time_end', models.TimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('difficulty', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WORKING_ON', 'Working on'), ('ON_HOLD', 'On Hold'), ('DONE', 'Done')], default='OPEN', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks_tagged', to='_global.tag')),
            ],
        ),
    ]
